//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrower
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Borrower()
        {
            this.OrderTbls = new HashSet<OrderTbl>();
        }
    
        public int borrowerID { get; set; }
        public string borrowerName { get; set; }
        public Nullable<System.DateTime> borrowerBirthDate { get; set; }
        public string borrowerGender { get; set; }
        public string borrowerAddress { get; set; }
        public string borrowerPhone { get; set; }
        public string borrowerEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderTbl> OrderTbls { get; set; }
    }
}
