//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderTbl()
        {
            this.DetailOrders = new HashSet<DetailOrder>();
        }
    
        public int orderID { get; set; }
        public Nullable<System.DateTime> dateBorrowed { get; set; }
        public Nullable<int> borrowerID { get; set; }
        public Nullable<System.DateTime> returnDate { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> librarianID { get; set; }
    
        public virtual Borrower Borrower { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailOrder> DetailOrders { get; set; }
        public virtual Librarian Librarian { get; set; }
        public virtual StatusObject StatusObject { get; set; }
    }
}
