//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyHistory
    {
        public int supplyID { get; set; }
        public Nullable<int> bookID { get; set; }
        public Nullable<int> librarianID { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<System.DateTime> supplyDate { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Librarian Librarian { get; set; }
    }
}
